routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'AuthController@showFormLogin')->name('login');
Route::get('login', 'AuthController@showFormLogin')->name('login');
Route::post('login', 'AuthController@login');
Route::get('register', 'AuthController@showFormRegister')->name('register');
Route::post('register', 'AuthController@register');

Route::group(['middleware' => 'auth'], function () {

    Route::get('home', 'HomeController@index')->name('home');
    Route::resource('pertanyaan', 'PertanyaanController')->except('create', 'edit');
    Route::get('progress', 'ProgressController@index')->name('progress');
    Route::get('table', 'TableController@index')->name('table');
    Route::get('logout', 'AuthController@logout')->name('logout');

});

app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    protected $table = 'pertanyaan';
    protected $fillable = [
        'profil_id', 'judul', 'isi'
    ];
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;
use App\Pertanyaan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PertanyaanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pertanyaan = Pertanyaan::orderBy('created_at', 'desc')->get();

        return view('pages.pertanyaan.index')->with(compact('pertanyaan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'judul' => 'required',
            'isi'   => 'required',
        ]);

        Pertanyaan::create([
            'judul'     => $request->input('judul'),
            'isi'       => $request->input('isi'),
            'profil_id' => $request->user()->id
        ]);

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pertanyaan = Pertanyaan::findOrfail($id);
        return view('pages.pertanyaan.show')->with(compact('pertanyaan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'isi'      => 'required',
            'judul'     => 'required',
        ]);

        $pertanyaan = Pertanyaan::findOrfail($id);

        $pertanyaan->isi = $request->input('isi');
        $pertanyaan->judul = $request->input('judul');
        $pertanyaan->update();

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pertanyaan = Pertanyaan::find($id);
        $pertanyaan->delete();
        return redirect('pertanyaan');
    }
}

resources/views/pages/pertanyaan/index.blade.php
@extends('admin.master')
@section('content')
<div class="modal fade" id="new" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Buat Pertanyaan</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{{ route('pertanyaan.store') }} ">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label>Judul</label>
                        <input required name="judul" value="" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Isi</label>
                        <input required name="isi" value="" type="text" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="content-header d-flex flex-column flex-md-row mb-3">
    <div class="row">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item active" aria-current="page">Semua Pertanyaan</li>
            </ol>
        </nav>
    </div>
    <div class="wrapper ml-0 ml-md-auto my-auto d-flex align-items-center pt-4 pt-md-0">
      <button data-toggle="modal" data-target="#new"  class="btn btn-success btn-sm ml-auto">Tambah Baru</button>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                {{-- <div class="form-group">
                    <input id="search" type="search" class="form-control" placeholder="Search Here / invoice / nama lengkap">
                </div> --}}
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    #
                                </th>
                                <th>
                                    Judul
                                </th>
                                <th>
                                    Isi
                                </th>
                                <th>
                                    Dibuat
                                </th>
                            </tr>
                        </thead>
                        <tbody id="index_query">
                            @foreach ($pertanyaan as $key => $item)
                            <tr>
                                <td>{{ $key + 1 }}</td>
                                <td><a href="/pertanyaan/{{ $item->id }}">{{$item->judul}}</td>
                                <td>{{ $item->isi }}</td>
                                <td>{{ date('d F Y H:i', strtotime($item->created_at)) }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/pertanyaan/show.blade.php
@extends('admin.master')
@section('content')
<div class="content-header d-flex flex-column flex-md-row mb-3">
    <div class="row">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0">
                <li class="breadcrumb-item" aria-current="page"><a href="/pertanyaan">Semua pertanyaan</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{$pertanyaan->judul}}</li>
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="POST" action="{{route('pertanyaan.update', $pertanyaan->id)}}">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Judul</label>
                            <input required name="judul" value="{{$pertanyaan->judul}}" type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Isi</label>
                            <input required name="isi" value="{{$pertanyaan->isi}}" type="text" class="form-control">
                        </div>
                    </div>
                    <button type="submit" name="_method" value="put" class="btn btn-primary">Ubah Data</button>
                    <button type="submit" name="_method" value="delete" class="btn btn-danger">Hapus</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection